Project
ChValeriya/project-2 pull request #1
Opened 2022-01-30 11:13 UTC by ChValeriya

Added header, sections "hero", "main", "using"

2022-01-30 12:05 UTC, aleksey-drozdov requested changes

2022-01-30 12:05 UTC, aleksey-drozdov commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@400;700&display=swap" rel="stylesheet">
эта ссылка уже не нужна, т.к. мы подключаем локальные шрифты

2022-01-30 12:05 UTC, aleksey-drozdov commented on index.html
> +                    <h6 class="text__name">AENEAN CONSECTETUR<h6>
закрытие тега h6 с ошибкой написанно

2022-01-30 12:05 UTC, aleksey-drozdov commented on index.html
> +                    <h6 class="text__name">CONSECTULTRICIES<h6>
ошибка в закрытии тега

2022-01-30 12:05 UTC, aleksey-drozdov commented on index.html
> +                    <botton><a class="botton__text" href="#">Get the App</a></botton>
ошибка в теге кнопки. button )

2022-01-30 13:58 UTC, ChValeriya commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@400;700&display=swap" rel="stylesheet">
удалила

2022-01-30 13:59 UTC, ChValeriya commented on index.html
> +                    <h6 class="text__name">AENEAN CONSECTETUR<h6>
исправила

2022-01-30 13:59 UTC, ChValeriya commented on index.html
> +                    <h6 class="text__name">CONSECTULTRICIES<h6>
исправила

2022-01-30 13:59 UTC, ChValeriya commented on index.html
> +                    <botton><a class="botton__text" href="#">Get the App</a></botton>
исправила

2022-02-01 07:47 UTC, aleksey-drozdov approved these changes
После того, как зальёте этот ПР нужно обновить дев и подтянуть его в другую ветку, где создан ПР, что бы убрать дублирование кода

2022-02-01 17:28 UTC, merged